name: Build Unity APK
on:
  workflow_dispatch: {}
  # push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   

      # - uses: actions/cache@v3
      #   with:
      #     path: Library
      #     key: Library-personalTest-Android
      #     restore-keys: |
      #       Library-personalTest-
      #       Library-
          
      - name: Buuild APK
        uses: game-ci/unity-builder@v4
        id: thebuildstep
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          # buildName: somethingforNOW
          # buildsPath: allmybuilds

      - name: Save APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build ${{ steps.myBuildStep.outputs.buildVersion }}
          path: build
          
          # name: test
          # path: /github/workspace/allmybuilds/Android/
          # retention-days: 1 
          # overwrite: true

