name: TestFlow
on: 
  workflow_dispatch: {}
  # push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        run: |
          b="$GITHUB_REF"
          b=$(sed 's/^refs\/heads\///' <<< "$b")
          b=$(sed 's/\//-/g' <<< "$b")
          echo "BNAME=$b" >> $GITHUB_ENV

      - name: UseENV
        run: |
          echo "The variable is $BNAME"
          
