name: TestFlow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
      - name: Print branch name
        env:
          BRANCH_NAME: $BRANCH_NAME
        run: |
          echo "Branch name: $BRANCH_NAME"
